### ISSUE TITLE
Transfering objects via sockets.

### ISSUE THREAD

**Issue by JNicL** [gsec/eZchat#10]
Transfering objects via sockets can be done, for instance, with pickle ( or cPickle for better performing). Pickle serializes objects which can be represented as strings via the dumps methods. In particular, this allows us to make use of the ordinary recv and send methods. I've tested the module and it works amazingly well, so actually, the problem is alrdy solved and must yet be implemented.

**Comment by bijancn** [comment]
So how is the status here? Solved?
