### ISSUE TITLE
Database progress

### ISSUE THREAD

**Issue by JNicL** [gsec/eZchat#13]
I need a working database with sync. In particular, I need the methods:
- Are two databases equal (via hash maybe?)
- Which entries need to be synced?

Is there anyone willing to take care of this job (as fast as possible please)?

**Comment by bijancn** [comment]
I'm currently in a meeting till Thursday and cannot work on this until then. There have been problems with the database (dictionaries put in are not the same as the ones which come out) but with contact with the authors of dataset I now know how to fix it. I guess I could have a working solution around Sunday.

I would suggest to fake the functionalities until you have them. I would suggest as interface 

```
  msg_list -> returns list of ID's in message database
  necessary_msg (msg_list) -> Given a list of ID's, 
                  return a list of ID's that are not in the local message database
  msgs_of_IDs (msg_ID_list) -> Return a list of dictionaries given a list of IDs
  add_msgs (msg_list) -> Add the list of dictionaries/messages to the local database
```

So far, so clear? Suggestions for better network communication?
