### ISSUE TITLE
User database

### ISSUE THREAD

**Issue by bijancn** [gsec/eZchat#14]
The user database has a similar but different structure to the message database. I will next be working on a nonugly refactoring of the common part of those two databases. Sadly the API of Database will slightly change due to that but it should be easy to fix or will be fixed by me when I commit.

@gsec @crossbow911 @JNicL : As I think it would be a good idea to store the IPs and public keys next to the users, would you say it might be a good protocol to just have an sql-file on the ftp_server with which users synchronize, similar to the message database syncs? I.e. when you connect, you update the IP of your user in the database.

The next step could be to use a symmetric encryption of the user data, in the sense that you have to know the group name and password to be able to connect to the users of the group.

Please comment, it feels like an epiphany right now ;)

**Comment by gsec** [comment]
IP+pubkeys in a db sounds nice. Probably we should also have a history of IPs, e.g. last 5 connections or so. That would allow for a better network coverage, if you logged in from elsewhere, but the next time you might still provide a node with your previous IP at home or s.th.
Also i a good approach could be having the groups in the user db as meta-users, to which you can write your messages, with keys and acess provided to all members.

**Comment by JNicL** [comment]
My wishlist:
-Given the UID I want  a method returning the associated ip/port tuple.
-Given the UID I want to update the ip/port tuple to a new value.

**Comment by bijancn** [comment]
Reopen when you want more. At the moment, I don't see what is still missing..
