### ISSUE TITLE
eZchat has to be renamed to verYcomPlicatedChat

### ISSUE THREAD

**Issue by gsec** [gsec/eZchat#17]
Just tried to fix the build status, but:

ez_client <- ez_user_methods <-- ez_process <-- ez_contact <-- ez_process_base <-- object
while ez_process_base.__metaclass__ = ez_process_base_meta, which inherits from type ... etc.

And this is just _one_ example.
While multiple inheritance and metaclasses might be supercool, this ain't physics! ==> Just because we can, we should not do it. Is this necessary? I strongly believe not.
Combined with lacking test modules, the code is becoming unhandleable. This requires to be fixed, and fixed soon! **Before** "just getting it to work" (http://en.wikipedia.org/wiki/Technical_debt)

If this is really necessary we need at least to clarify the structure and have a concept in mind.
(have very few base classes from which to inherit general functions, flat hierarchy etc.)
As of now, I do not have the full overview of the programming structure, so this is only my point of view.
But chances are, that if this isn't fixed, nobody will understand it in the future.

_While assigned to @JNicL as he would have to coordinate this, I think this should be discussed and worked on by everyone._

**Comment by bijancn** [comment]
I am a bit confused why the build has been broken but never fixed again. The so called '<- last commit' from @JNicL seems to be the culprit. Does anyway understand what has gone wrong there? I certainly do not ^^.

Concerning the module hierarchy, I would say ez_chat is still at a quite maintainable level. I am not proud of the cyclic dependency between ez_user and ez_crypto but it works and IMHO not worth the effort of rewriting. We have a lot of modules at the bottom (either external or minimal) which you can just ignore in deps.pdf: sys, os, Crypto, dataset, ez_preferences, cPickle, types, Queue, thread, threading, urwid, collections, subprocess, PyQt4. Actually also half of the bubbles would disappear in the plot when we would only include one module per line ;). Projecting all of this out, you see that ez_user_methods encapsulates all the 'chat functionality' like an API that can be called by either the GUI or the CLI or some third-party application. Maybe we should rename ez_user_methods -> ez_api. I hope I understood it correctly.

There is some strange stuff lying around as some people don't like cleaning up. What exactely is the use of ez_client? Was this necessary for threading with urwid? If so please rename, else delete if possible. I guess keys has never evolved from being just a draft, right? Can we delete? Will we keep ez_server as executable to run on Rasperry? Please document. ez_main is also not used anymore right? Can we delete?

When it comes to ez_process, however, I totally agree with you. @JNicL is the only one who will ever understand this code ^^ but I guess as long as the meta classes stay there and don't infect other modules, it is ok. But as such he also should fix the build when he breaks it :)

**Comment by JNicL** [comment]
@bijancn regarding ez_client: ez_client.py is is needed to start a new independent process of the cli/gui. We can rename it to whatever you like, but we cannot delete it. 
@gsec I will fix the built. As for the Big picture, I have the idea to separate low-level from high-level processes. As bijancn has correctly realized, i want to make it possible that users can write their own extensions. For instance, you may want to write a brackground ping process, which does nothing but frequently ping your contacts. This is possible by the use of low-level processes (e.g. ez_background_process). By encapsulating your new method in a class with the ez_process meta (which is done automatically if you inherit from ez_process!), your function will automatically be accessible by ez_p2p without further intervention.

**Comment by bijancn** [comment]
This sounds very reasonable. Maybe you want to put a bit of documentation at the top of the module. Not much just enough such that a user (like me or gui) could easily (within an hour) implement a function and show how to test if it is actually working.

**Comment by gsec** [comment]
I am not talking about depencies and how deps.dot looks like with the imported modules. This might also be a part, but will get better in a cleanup. The main thing I am concernded is, that the list at the beginning are not module dependencies, but is just one path in the classes _inheritance_ tree... 

The concept of low-lvl/high-lvl is nice, and I will look into that further. Nevertheless `super()` should be used as scarce as possible, as it makes the code unclear, especially if there is another super() in it and so on. 
So, then the idea might be, that if it is not absolutely needed, we inherit from ez_process_meta and not from ez_process, as an example of keeping the hierarchy flat.

_"@JNicL is the only one who will ever understand this code"_ yes, this is exactly my concern. And this is **_bad_**. The efforts should be in the direction to change this, by restructuring and documentation.

**Comment by bijancn** [comment]
So we agree that the only problem is `ez_process` and the rest is rather fine. In `ez_cli` I have started to use an explicit `urwid.Edit.__init__(self, **kwargs)` instead of `self.__super.__init__(*args, **kwargs)`. When we have simple inheritance the benefit is only better readability, I think. I do not understand exactely how `super` plays with meta-classes. Anyway, the hierarchy in `ez_process` is also more or less straightforward: 
- there is `ez_process_base_meta` defining the basic process structure and registering functionalities and attributes
- `ez_process_base` is obviously black magic initiating the meta class? Does the init in there do anything? There doesn't seem to be a link to `ez_process_base_meta` neither via inheritance nor explicitely.
- then we have `ez_background_process`, `ez_contact`, `ez_db_sync`, `ez_packet` that all inherit from `ez_process_base` and are either directly inherited by ez_process or via a step in between like `ez_ping`. If it helps with refactoring and is logically reasonable (like `ez_background_process`), I would encourage those steps inbetween though it might be a bit confusing for new developers at first. matplotlib has some more levels of multiple inheritance in it.

**Comment by bijancn** [comment]
Documentation is pretty nice know. Check it out: http://ezchat.readthedocs.org ! With automatic inheritance diagrams for each module. Procrastination ftw.

**Comment by bijancn** [comment]
@gsec Can we close this now or what remains to be done?
