### ISSUE TITLE
Make Gui resizable

### ISSUE THREAD

**Issue by bijancn** [gsec/eZchat#2]
As discussed, the text windows don't rescale with the main window as they should

**Comment by gsec** [comment]
Gui ist ausgewachsen, und bleibt jetzt so gross (sry^^)

**Comment by JNicL** [comment]
dafuq?  Uli worked with QT too, he might fix this!

**Comment by bijancn** [comment]
You can obviously assign him as well.. Didn't know that and I still have no clue about QT :)

**Comment by bijancn** [comment]
Or not ?? Is it only possible to assign one person? Ok @crossbow911 challenge accepted? I guess @JNicL also has to think about sockets ;)

**Comment by bijancn** [comment]
Fixed by 7d619c1d9d3bf07ff2f948f45a08a371b9505b15. Looks nice though I have some immediate new wishes which will go in #5.
