### ISSUE TITLE
Crypto & Librarys

### ISSUE THREAD

**Issue by gsec** [gsec/eZchat#4]
Crypto Library before => [`pycrypto`](https://www.dlitz.net/software/pycrypto/)
Crypto Library as of now  => [`Python-RSA`](http://stuvel.eu/files/python-rsa-doc/index.html)
#### pycrypto:

++ 
- lots of crypto tools and schemes
  - `RSA`, `AES`, `ElGamal`, cryptographicall strong RNG, hashes etc.
- seems widely used, in pypi
- a little trustworthy

-\- 
- lots of things
- not well documented 
- unexpected workflow, behaviour
#### Python-RSA

++
- does exactly what we need
  - `RSA`, `VAR_BLOCK`
- well documented

--
- does not more than that
- random students from amsterdam
  - not so trustworthy
- `VAR_BLOCK` only works on files
### so what?

RSA encrypts messages of lengt_key - overhead_bytes. That means a 1024 bit key 
can only encode ~ 90 bytes. The solutions I found so far:
- use RSA (asymmetric) to encode a random AES-key (symmetric) and send it along 
  with the message, symmetrically encrypted.
- Chop down the message into small bits and encode one at a time, put them 
  together, and send it. Recipient of course inverts the operation.
  This is exactly what `VAR_BLOCK` does. Unfortunately this only works on files, 
  giving me some headache, but should be feasible and not the issue here.

---

Crypto is hard! That means, if you make a small mistake in the implementation 
it is useless! Therefore we should implement as little as possible ourselves, 
and rely on (hopefully) more tested librarys.

I would like to hear your comments and suggestions on those issues.

**Comment by bijancn** [comment]
Mhhh .. from the quick google / stackoverflow survey there really doesn't seem to be an immediate pythonic secure solution :(. What I see a lot and looks very good is [keyczar](http://code.google.com/p/keyczar/). Has a very simple interface and the documentation seems to be quite complete. I wouldn't trust any small project like the Amsterdam sutdents to get it right. 

Maybe try it out and when it solves all your problems, we add a dependency but have most likely a very safe solution.

**Comment by gsec** [comment]
I do not see the advantage of `keyczar`, since the documentation is old/inconsistent. Advantage of `Python-RSA` was clean documentation, everyone knows what function does what. If they are not trustworthy, why should be keyczar? They build on top of `PyCrypto`, and so should we, by lack of alternatives. I do not see an advantage there. Except anyone has productive ideas, issue should be closed.

**Comment by JNicL** [comment]
I would have sticked to keyczar, but apparently u've decided otherwise and so it is decided: the hard way - pycrypto.
