### ISSUE TITLE
GUI - Add word wrapping and scroll back mode

### ISSUE THREAD

**Issue by bijancn** [gsec/eZchat#5]
Our beautiful UI has to wrap messages that are too long to display into multiple lines.

Furthermore, it has to be possible to scroll back when there are too many lines to show in one window.

**Comment by crossbow911** [comment]
messages longer than 80 characters are displayed in multible lines

**Comment by bijancn** [comment]
Well this is not quite the expected behaviour IMHO. Compare e.g. to HipChat. As I make the window smaller, the text is wrapped and words are distributed on more and more lines.
