### ISSUE TITLE
Fuse ezc_main with ezc_connection and ezc_database

### ISSUE THREAD

**Issue by bijancn** [gsec/eZchat#7]
As soon as we are in a working state with the connections and database, we should fuse them with the UI.

But for now I think @crossbow911 basic history solution is good enough for testing.

**Comment by JNicL** [comment]
I added a new ezc_main_to_be_merged. I was unable to merge mine with ulis new one since he removed the base class instance. I think the gui should be encapsulated in a class allowing to deal easily with update routines etc. U can test the new client and server via  ezc_main_to_be_merged.py.

**Comment by bijancn** [comment]
I guess, this ticket evolves into use first ez_database with ez_p2p for users and messages and add a main at the end that uses ez_cli and ez_p2p.. It should be done in a way that makes it obvious how to change the global loop minimally when using ez_gui instead of ez_cli ..
