### ISSUE TITLE
filespace and naming

### ISSUE THREAD

**Issue by gsec** [gsec/eZchat#8]
There probably should be mainly modules in root dir ezc_modulename readme and license, but other files go into subdirs (history, database etc.)
Every file has a clear name of what it does, versioning is done with git,  not with ui02 ui123.. !
Please rename functions, to NOT be author_xxth_whatever()
Again, comments should be helpful, not storage of obsolete stuff -> git does versioning.

**Comment by bijancn** [comment]
@JNicL @crossbow911 please clean up. Don't worry about deleting files. You can always get them back with git. I don't know which of `ui.ui, uli.py, ui02.py, server.py, client.py ezc_ui.py` is being used and which is obsolete. I would expect to see one `ezc_connection.py` and one `ezc_ui.py`.

**Comment by JNicL** [comment]
Well, I will clean up, sooner or later and currently I'm working on it. Maybe I should start a new branch since it will take quite some time until finished.

**Comment by gsec** [comment]
@JNicL can ez_client, ez_server be removed?
@crossbow911 which ui files are needed?
Please remove obsolete versions.
